### PR TITLE
use strict types always

### PR DESCRIPTION
**Pull request by lukadschaak**

### CODE REVIEW

**Review by jdreesen — APPROVED** [review]
You should also enable the CS-Fixer rule to enforce this.

**Comment by lukadschaak** [comment]
> You should also enable the CS-Fixer rule to enforce this.

i throught about that, but wanted to keep the cs-fixer config as small as possible.

There is also the problem, that two rules are needed to force declare in the same line as the php opening tag

**Comment by jdreesen** [comment]
Afaik, PhpStorm doesn't have this by default in its templates, which would mean that everyone would have to add it manually, and it *will* be forgotten. That's why I think it's a task for the CS fixer.

**Comment by lukadschaak** [comment]
Think so as well. So i updated the cs-fixer config

**Review by jdreesen — APPROVED** [review]

**Pull request merged**
